local_apps/pootle_translationproject/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2008 Zuza Software Foundation
#
# This file is part of Pootle.
#
# Pootle is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Pootle is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pootle; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

from django.conf.urls.defaults import *
urlpatterns = patterns('pootle_translationproject.views',
    (r'^(?P<language_code>[^/]*)/(?P<project_code>[^/]*)/((.*/)*)admin_permissions.html$',
     'tp_admin_permissions'),
    (r'^(?P<language_code>[^/]*)/(?P<project_code>[^/]*)/((.*/)*)admin_files.html$',
     'tp_admin_files'),
    (r'^(?P<language_code>[^/]*)/(?P<project_code>[^/]*)/(?P<dir_path>(.*/)*)(index.html)?$',
     'tp_overview'),
    (r'^(?P<language_code>[^/]*)/(?P<project_code>[^/]*)/(?P<dir_path>.*)edit.html$',
     'tp_translate'),
    (r'^(?P<language_code>[^/]*)/(?P<project_code>[^/]*)/(?P<dir_path>.*)review.html$',
     'tp_review'),
    (r'^(?P<language_code>[^/]*)/(?P<project_code>[^/]*)/(?P<file_path>.*)export/zip$',
     'export_zip'),
    (r'^(?P<language_code>[^/]*)/(?P<project_code>[^/]*)/translate.html$',
     'translate'),
)

pootle/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2008-2009 Zuza Software Foundation
#
# This file is part of Pootle.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.

from django.conf.urls.defaults import *
from django.conf import settings
from os import path

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

DJANGO_MEDIA = path.join(path.dirname(admin.__file__), 'media')

urlpatterns = patterns('',
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    (r'^django_admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^django_admin/(.*)', admin.site.urls),

    # Static and media files
    (r'^html/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^(favicon.ico)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': DJANGO_MEDIA}),
    # direct download of translation files
    (r'^export/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.PODIRECTORY}),
    # documentation
    (r'^docs/(?P<docfile>.*)$', 'django.views.generic.simple.direct_to_template', {'template': "docs.html"}),
    # External Apps
    (r'^contact/', include('contact_form_i18n.urls')),
    (r'^accounts/', include('pootle_profile.urls')),
    (r'^articles/', include('wt_articles.urls')),
    # Pootle urls
    (r'^projects/', include('pootle_project.urls')),
    (r'', include('pootle_notifications.urls')),
    (r'', include('pootle_terminology.urls')),
    (r'', include('pootle_store.urls')),
    (r'', include('pootle_app.urls')),
    (r'', include('pootle_translationproject.urls')),
    (r'', include('pootle_language.urls')),
)

urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# 
# Copyright 2008 Zuza Software Foundation
# 
# This file is part of translate.
#
# translate is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# translate is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with translate; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

from django.conf.urls.defaults import *
from django.conf import settings
from os import path

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

CSS_DIR    = settings.MEDIA_ROOT
IMAGES_DIR = path.join(settings.MEDIA_ROOT, 'images')
JS_DIR     = path.join(settings.MEDIA_ROOT, 'js')
DJANGO_MEDIA = path.join(path.dirname(admin.__file__), 'media')

urlpatterns = patterns('',
    # Example:
    # (r'^pootle_app/', include('pootle_app.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^media/(?P<path>.*)$',  'django.views.static.serve', {'document_root': DJANGO_MEDIA}),
    (r'^django_admin/(.*)', admin.site.root),
    (r'^(?P<path>.*[.]css)$',  'django.views.static.serve', {'document_root': CSS_DIR}),
    (r'^(?P<path>(:?images|js|doc)/.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^login.html$', 'Pootle.views.auth.login'),
    (r'^logout.html$', 'Pootle.views.auth.logout'),
    (r'^admin', include('Pootle.views.admin.urls')),
    (r'^home',  include('Pootle.views.home.urls')),
    (r'^projects', include('Pootle.views.projects.urls')),
    (r'^robots.txt$', 'Pootle.views.index.view.robots'),
    (r'^about.html$', 'Pootle.views.index.view.about'),
    (r'^register.html$', 'Pootle.views.index.view.register'),
    (r'^activate.html$', 'Pootle.views.index.view.activate'),
    (r'^(/|/index.html)?$', 'Pootle.views.index.view.index'),
    (r'', include('Pootle.views.language.urls')),
)

local_apps/pootle_translationproject/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2009 Zuza Software Foundation
#
# This file is part of Pootle.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.

"""Form fields required for handling Translation Project"""
from django import forms
from django.utils.translation import ugettext_lazy as _

class SearchForm(forms.Form):
    search = forms.CharField(widget=forms.TextInput(attrs={'size': '15'}))
    sfields = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple,
                                              choices=(('source', _('Source Text')),
                                                       ('target', _('Target Text')),
                                                       ('notes', _('Comments')),
                                                       ('locations', _('Locations'))),
                                              initial=['source', 'target'])

local_apps/pootle_translationproject/templates/translation_project/fileop_forms.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% if upload %}
<div id="upload" class="module first clear" lang="{{ LANGUAGE_CODE }}">
    <div class="bd">
        <h2>{{ upload.form.title }}</h2>
        <form action="" method="post" class="upload" id="uploadform" name="uploadform" enctype="multipart/form-data">
          {{ form.non_field_errors }}
          {% for field in upload.form %}
          <p {% if field.help_text %}title="{{ field.help_text }}"{% endif %}>
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
          </p>
          {% endfor %}
          <p class="common-buttons-block">
              {{ upload.render_submits }}
          </p>
        </form>
    </div>
</div>
{% endif %}
{% if update %}
<div id="update" class="module first clear" lang="{{ LANGUAGE_CODE }}">
    <div class="bd">
        <form action="" method="post" class="vcs-update" name="updateform" enctype="multipart/form-data">
        {{ update.as_p }}
        </form>
    </div>
</div>
{% endif %}

local_apps/pootle_translationproject/templates/translation_project/search.html
{% load i18n baseurl %}

{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

<div id="search" lang="{{ LANGUAGE_CODE }}" dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}">
  <form action="{{ search_action }}" method="get" id="searchform">
    <label class="inputHint" for="id_search">{% trans "Search" %}</label>{{ search_form.search }}
    <a class="advancedlink">
      {% if LANGUAGE_BIDI %}
      <img src='{{ "images/sarrow_down_rtl.png"|m }}' alt="{{ advanced_search_title }}" title="{{ advanced_search_title }}" class="togglesearch" />
      <img src='{{ "images/sarrow_up_rtl.png"|m }}' alt="{{ advanced_search_title }}" title="{{ advanced_search_title }}" class="togglesearch" style="display: none;"/>
      {% else %}
      <img src='{{ "images/sarrow_down.png"|m }}' alt="{{ advanced_search_title }}" title="{{ advanced_search_title }}" class="togglesearch" />
      <img src='{{ "images/sarrow_up.png"|m }}' alt="{{ advanced_search_title }}" title="{{ advanced_search_title }}" class="togglesearch" style="display: none;"/>
      {% endif %}
    </a>
    <div class="advancedsearch">
      {{ search_form.sfields }}
    </div>
  </form>
</div>

local_apps/pootle_translationproject/templates/translation_project/tp_admin_files.html
{% extends "tp_base_admin.html" %}

{% load i18n baseurl %}

{% block title %}
{{ block.super }} » {% trans "Files" %}
{% endblock %}

{% block bodyclass %}tpadminfiles{% endblock %}

{% block section_description %}{% trans "Here you can manage the files in this translation project." %}
<div id="filesmanage">
  <form action="" method="post">
    <div class="admin-buttons-block" lang="{{ LANGUAGE_CODE }}" dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}">
      <input type="submit" class="update" name="template_update" value='{% trans "Update files from templates" %}' />
      <input type="submit" class="rescan" name="scan_files" value='{% trans "Rescan project files" %}' />
    </div>
  </form>
</div>
{% endblock %}

{% block section_body %}
{% include "admin/admin_general.html" %}
{% endblock %}

{% block scripts_extra %}
{{ block.super }}
<script type="text/javascript" src='{{ "js/admin.js"|m }}'></script>
<script type="text/javascript" src='{{ "js/sorttable.js"|m }}'></script>
{% endblock %}

local_apps/pootle_translationproject/templates/translation_project/tp_admin_permissions.html
{% extends "tp_base_admin.html" %}

{% load baseurl i18n %}

{% block title %}
{{ block.super }} » {% trans "Permissions" %}
{% endblock %}

{% block bodyclass %}tpadminpermissions{% endblock %}

{% block section_body %}
<div class="settings-container centered" lang="{{ LANGUAGE_CODE }}">
    <p class="info">{% trans "Below you can add, edit, and delete the permissions for this translation project." %}</p>
    <p class="help">
      {% trans "The user “nobody” refers to any user that is not logged in (an anonymous, unidentified user). The user “default” refers to the rights that all logged in users will have by default, unless other specific rights were assigned to them." %}
    </p>
    {% include "admin/admin_general.html" %}
</div>
{% endblock %}

{% block scripts_extra %}
{{ block.super }}
<script type="text/javascript" src='{{ "js/admin.js"|m }}'></script>
{% endblock %}

local_apps/pootle_translationproject/templates/translation_project/tp_overview.html
{% extends "tp_base_extended.html" %}

{% load i18n baseurl %}

{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

{% block body.id %}fileindex{% endblock body.id %}

{% block bodyclass %}tpoverview{% endblock bodyclass %}


{% block content %}
{% if children %}
<!--! The statistics view -->
<div class="module-primary" lang="{{ LANGUAGE_CODE }}">
    <div class="bd">
        <table class="sortable stats" id="stats" cellpadding="5"
        cellspacing="0" width="100%" lang="{{ LANGUAGE_CODE }}" dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}">
            <thead>
                <tr>
                    <th class="stats">{{ stats_headings.name }}</th>
                    <th class="stats">{{ stats_headings.progress }}</th>
                    <th class="stats sorttable_numeric">{{ stats_headings.summary }}</th>
                    <th class="stats">{{ stats_headings.totalwords }}</th>
                </tr>
            </thead>
            <tbody class="stats">
                {% for item in children %}
                <tr class="item {% cycle 'even' 'odd' %}" title="{{ item.description }}">
                {% include "language/item_summary.html" %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endif %}
{% endblock content %}

{% block postcontent %}
{% include "translation_project/fileop_forms.html" %}
{% include "top_contributers_table.html" %}
{% endblock postcontent %}

{% block scripts_extra %}
{{ block.super }}
<script type="text/javascript" src='{{ "js/sorttable.js"|m }}'></script>
{% if upload %}
<script type="text/javascript">
$(document).ready(function() {
  $("select#id_upload_to_dir").parent().hide();
  $("input#id_file").change(function() {
    if (/\.zip$/.test($(this).val())) {
      $("select#id_upload_to").parent().hide();
      $("select#id_upload_to_dir").parent().show();
    } else {
      $("select#id_upload_to_dir").parent().hide();
      $("select#id_upload_to").parent().show();
    }
  });
});
</script>
{% endif %}
{% endblock %}

local_apps/pootle_translationproject/templates/translation_project/tp_review.html
{% extends "tp_base_extended.html" %}

{% load i18n %}

{% block title %}
{{ block.super }} » {% trans "Review" %}
{% endblock %}

{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

{% block bodyclass %}tpreview{% endblock bodyclass %}

{% block content %}
{% if children %}
<!-- The review view -->
{% for item in children %}
<div class="module-primary" lang="{{ LANGUAGE_CODE }}">
    <div class="bd">
        {% if item.isdir or item.isfile %}
        <div class="item {% cycle 'even' 'odd' %}">
        {% include "language/item_block.html" %}
        {% include "language/item_stats.html" %}
        </div>
        {% endif %}
    </div>
</div>
{% endfor %}
{% endif %}
{% endblock content %}

{% block postcontent %}
{% include "top_contributers_table.html" %}
{% endblock postcontent %}

local_apps/pootle_translationproject/templates/translation_project/tp_translate.html
{% extends "tp_base_extended.html" %}

{% load i18n %}

{% block title %}
{{ block.super }} » {% trans "Translate" %}
{% endblock %}

{% block bodyclass %}tptranslate{% endblock bodyclass %}

{% block content %}
<!-- The editing view -->
{% for item in children %}
<div class="module-primary" lang="{{ LANGUAGE_CODE }}">
    <div class="bd">
        {% if item.isdir or item.isfile %}
        <div class="item {% cycle 'even' 'odd' %}">
        {% include "language/item_block.html" %}
        {% include "language/item_stats.html" %}
        </div>
        {% endif %}
    </div>
</div>
{% endfor %}
{% endblock content %}

{% block postcontent %}
{% include "translation_project/fileop_forms.html" %}
{% include "top_contributers_table.html" %}
{% endblock postcontent %}

{% block scripts_extra %}
{{ block.super }}
{% if upload %}
<script type="text/javascript">
$(document).ready(function() {
  $("select#id_upload_to_dir").parent().hide();
  $("input#id_file").change(function() {
    if (/\.zip$/.test($(this).val())) {
      $("select#id_upload_to").parent().hide();
      $("select#id_upload_to_dir").parent().show();
    } else {
      $("select#id_upload_to_dir").parent().hide();
      $("select#id_upload_to").parent().show();
    }
  });
});
</script>
{% endif %}
{% endblock %}

local_apps/pootle_translationproject/templates/translation_project/translate_offline_notice.html
{% load i18n %}
<div class="translate-offline-notice">
  <div>{% blocktrans %}You can translate files offline using tools like <a class="external" href="http://virtaal.org">Virtaal</a> &mdash; just download any file in XLIFF format by clicking the <dfn>Translate offline</dfn> button, edit it on your computer, then upload it back using the <dfn>Upload Translated File</dfn> button at the top of the page.{% endblocktrans %}</div>
</div>