external_apps/profiles/urls.py
"""
URLConf for Django user profile management.

Recommended usage is to use a call to ``include()`` in your project's
root URLConf to include this URLConf for any URL beginning with
'/profiles/'.

If the default behavior of the profile views is acceptable to you,
simply use a line like this in your root URLConf to set up the default
URLs for profiles::

    (r'^profiles/', include('profiles.urls')),

But if you'd like to customize the behavior (e.g., by passing extra
arguments to the various views) or split up the URLs, feel free to set
up your own URL patterns for these views instead. If you do, it's a
good idea to keep the name ``profiles_profile_detail`` for the pattern
which points to the ``profile_detail`` view, since several views use
``reverse()`` with that name to generate a default post-submission
redirect. If you don't use that name, remember to explicitly pass
``success_url`` to those views.

"""

from django.conf.urls.defaults import *

from profiles import views


urlpatterns = patterns('',
                       url(r'^create/?$',
                           views.create_profile,
                           name='profiles_create_profile'),
                       url(r'^edit/?$',
                           views.edit_profile,
                           name='profiles_edit_profile'),
                       url(r'^(?P<username>[^/]+)/?$',
                           views.profile_detail,
                           name='profiles_profile_detail'),
                       url(r'^$',
                           views.profile_list,
                           name='profiles_profile_list'),
                       )

pootle/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2008-2009 Zuza Software Foundation
#
# This file is part of Pootle.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.

from django.conf.urls.defaults import *
from django.conf import settings
from os import path

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

DJANGO_MEDIA = path.join(path.dirname(admin.__file__), 'media')

urlpatterns = patterns('',
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    (r'^django_admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^django_admin/(.*)', admin.site.urls),

    # Static and media files
    (r'^html/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^(favicon.ico)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': DJANGO_MEDIA}),
    # direct download of translation files
    (r'^export/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.PODIRECTORY}),
    # documentation
    (r'^docs/(?P<docfile>.*)$', 'django.views.generic.simple.direct_to_template', {'template': "docs.html"}),
    # External Apps
    (r'^contact/', include('contact_form_i18n.urls')),
    (r'^accounts/', include('pootle_profile.urls')),
    (r'^articles/', include('wt_articles.urls')),
    # Pootle urls
    (r'^projects/', include('pootle_project.urls')),
    (r'', include('pootle_notifications.urls')),
    (r'', include('pootle_terminology.urls')),
    (r'', include('pootle_store.urls')),
    (r'', include('pootle_app.urls')),
    (r'', include('pootle_translationproject.urls')),
    (r'', include('pootle_language.urls')),
)

urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# 
# Copyright 2008 Zuza Software Foundation
# 
# This file is part of translate.
#
# translate is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# translate is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with translate; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

from django.conf.urls.defaults import *
from django.conf import settings
from os import path

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

CSS_DIR    = settings.MEDIA_ROOT
IMAGES_DIR = path.join(settings.MEDIA_ROOT, 'images')
JS_DIR     = path.join(settings.MEDIA_ROOT, 'js')
DJANGO_MEDIA = path.join(path.dirname(admin.__file__), 'media')

urlpatterns = patterns('',
    # Example:
    # (r'^pootle_app/', include('pootle_app.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^media/(?P<path>.*)$',  'django.views.static.serve', {'document_root': DJANGO_MEDIA}),
    (r'^django_admin/(.*)', admin.site.root),
    (r'^(?P<path>.*[.]css)$',  'django.views.static.serve', {'document_root': CSS_DIR}),
    (r'^(?P<path>(:?images|js|doc)/.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^login.html$', 'Pootle.views.auth.login'),
    (r'^logout.html$', 'Pootle.views.auth.logout'),
    (r'^admin', include('Pootle.views.admin.urls')),
    (r'^home',  include('Pootle.views.home.urls')),
    (r'^projects', include('Pootle.views.projects.urls')),
    (r'^robots.txt$', 'Pootle.views.index.view.robots'),
    (r'^about.html$', 'Pootle.views.index.view.about'),
    (r'^register.html$', 'Pootle.views.index.view.register'),
    (r'^activate.html$', 'Pootle.views.index.view.activate'),
    (r'^(/|/index.html)?$', 'Pootle.views.index.view.index'),
    (r'', include('Pootle.views.language.urls')),
)

local_apps/pootle_app/models/profile.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# 
# Copyright 2008 Zuza Software Foundation
# 
# This file is part of translate.
#
# translate is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# translate is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with translate; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import locale

from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User, UserManager, AnonymousUser
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save

from pootle.i18n.override import lang_choices

from pootle_misc.baseurl import l

from pootle_app.models.language import Language
from pootle_app.models.project import Project

        
class PootleUserManager(UserManager):
    """A manager class which is meant to replace the manager class for the User model. This manager
    hides the 'nobody' and 'default' users for normal queries, since they are special users. Code
    that needs access to these users should use the methods get_default_user and get_nobody_user."""
    def get_default_user(self):
        return super(PootleUserManager, self).get_query_set().select_related(depth=1).get(username='default')

    def get_nobody_user(self):
        return super(PootleUserManager, self).get_query_set().select_related(depth=1).get(username='nobody')

    def hide_defaults(self):
        return super(PootleUserManager, self).get_query_set().exclude(username__in=('nobody', 'default'))

# Since PootleUserManager has no state, we can just replace the User manager's class with PootleUserManager
# to get the desired functionality.
User.objects.__class__ = PootleUserManager

class PootleProfileManager(models.Manager):
    def get_query_set(self):
        return super(PootleProfileManager, self).get_query_set().select_related(
            'languages', 'projects', 'alt_src_langs')
    
class PootleProfile(models.Model):
    objects = PootleProfileManager()
    class Meta:
        app_label = "pootle_app"

    # This is the only required field
    user = models.OneToOneField(User, unique=True, db_index=True)

    unit_rows       = models.SmallIntegerField(default=10)
    input_height    = models.SmallIntegerField(default=5)
    languages       = models.ManyToManyField(Language, blank=True, limit_choices_to=~Q(code='templates'), related_name="user_languages", db_index=True)
    projects        = models.ManyToManyField(Project, blank=True, db_index=True)
    ui_lang         = models.CharField(max_length=50, blank=True, null=True, choices=(choice for choice in lang_choices()), verbose_name=_('Interface Language'))
    alt_src_langs   = models.ManyToManyField(Language, blank=True, db_index=True, limit_choices_to=~Q(code='templates'), related_name="user_alt_src_langs")

    def __unicode__(self):
        return self.user.username
    def get_absolute_url(self):
        return l('/accounts/%s/' % self.user.username)
    
    def _get_status(self):
        #FIXME: what's this for?
        return "Foo"

    status = property(_get_status)
    isopen = property(lambda self: True)

    def _get_pootle_user(self):
        if self.user_id is not None:
            return self.user
        else:
            return AnonymousUser()

    def getuserstatistics(self):
        """ get user statistics for user statistics links"""
        from pootle_app.models.suggestion import _get_suggestions
        userstatistics = []
        userstatistics.append({'text': _('Suggestions Accepted'), 'count': _get_suggestions(self, "accepted").count()})
        userstatistics.append({'text': _('Suggestions Pending'), 'count': _get_suggestions(self, "pending").count()})
        userstatistics.append({'text': _('Suggestions Reviewed'), 'count': self.suggestions_reviewer_set.count()})
        userstatistics.append({'text': _('Submissions Made'), 'count': self.submission_set.count()})
        return userstatistics

    def getquicklinks(self):
        """gets a set of quick links to user's project-languages"""
        from pootle_translationproject.models import TranslationProject
        from pootle_app.models.permissions import check_profile_permission
        quicklinks = []
        # TODO: This can be done MUCH more efficiently with a bit of
        # query forethought.  Why don't we just select all the
        # TranslationProject objects from the database which match the
        # user's Languages and Projects? This should be efficient.
        #
        # But this will only work once we move TranslationProject
        # wholly to the DB (and away from its current brain damaged
        # half-non-db/half-db implementation).
        
        for language in Language.objects.filter(user_languages=self):
            langlinks = []
            for translation_project in TranslationProject.objects.filter(
                language=language, project__pootleprofile=self):
                isprojectadmin = check_profile_permission(self, 'administrate',
                                                          translation_project.directory)

                langlinks.append({
                    'code': translation_project.project.code,
                    'name': translation_project.project.fullname,
                    'isprojectadmin': isprojectadmin,
                    })

            islangadmin = check_profile_permission(self, 'administrate', language.directory)
            quicklinks.append({'code': language.code,
                               'name': language.localname(),
                               'islangadmin': islangadmin,
                               'projects': langlinks})
            quicklinks.sort(cmp=locale.strcoll, key=lambda dict: dict['name'])
        return quicklinks

    pootle_user = property(_get_pootle_user)


def create_pootle_profile(sender, instance, **kwargs):
    """A post-save hook for the User model which ensures that it gets an
    associated PootleProfile."""
    try:
        profile = instance.get_profile()
    except PootleProfile.DoesNotExist:
        profile = PootleProfile(user=instance)
        profile.save()

post_save.connect(create_pootle_profile, sender=User)

def get_profile(user):
    """Return the PootleProfile associated with a user.

    This function is only necessary if 'user' could be an anonymous
    user.  If you know for certain that a user is logged in, then use
    the .get_profile() method on a user instead."""
    if user.is_authenticated():
        # Return the PootleProfile associated with authenticated users
        return user.get_profile()
    else:
        # Anonymous users get the PootleProfile associated with the 'nobody' user
        return User.objects.get(username='nobody').get_profile()

templates/profiles/edit_personal.html
{% extends "user_profile_base_extended.html"  %}
{% load i18n %}
 
{% block title %}
{{ block.super }} » {% trans "Profile" %}
{% endblock %}

{% block bodyclass %}profile{% endblock %}

{% block breadcrumb_content %}
{{ block.super }} » {% trans "Profile" %}
{% endblock %}

{% block section_description %}{% trans "Here you can change your personal details. This information will be used in the header of the translation files." %}{% endblock %}

{% block section_body %}
<form method="post" action="">
    <p>
        <label for="id_first_name">{% trans 'First Name' %}</label>
        {{ form.first_name }}
        {{ form.first_name.errors }}
    </p>
    <p>
        <label for="id_last_name">{% trans 'Last Name' %}</label>
        {{ form.last_name }}
        {{ form.last_name.errors }}
    </p>
    <p>
        <label for="id_email">{% trans 'Email address' %}</label>
        {{ form.email }}
        {{ form.email.errors }}
    </p>
    <p class="common-buttons-block">
        <input type="submit" class="save" value="{% trans 'Save' %}" />
    </p>
</form>
{% endblock %}

templates/profiles/edit_profile.html
{% extends "user_profile_base_extended.html"  %}
{% load i18n baseurl %}
 
{% block title %}
{{ block.super }} » {% trans "Translation Settings" %}
{% endblock %}

{% block bodyclass %}settings{% endblock %}

{% block breadcrumb_content %}
{{ block.super }} » {% trans "Translation Settings" %}
{% endblock %}

{% block section_description %}{% trans "Here you can configure the settings related to the translation interface as well as your language preferences." %}{% endblock %}

{% block section_body %}
<form method="post" action="">
  {{ form.non_field_errors }}
  {% for field in form %}
  <p>{{ field.errors }}
    {{ field.label_tag }} {{ field }}
    {% if field.help_text %}<span class="help_text">{{ field.help_text }}</span>{% endif %}
  </p>
  {% endfor %}
  <p class="common-buttons-block">
      <input type="submit" class="save" value="{% trans 'Save' %} "/>
  </p>
</form>
{% endblock %}

{% block scripts_extra %}
<script type="text/javascript" src="{{ "js/admin.js"|m }}"></script>
{% if LANGUAGE_BIDI %}
<script type="text/javascript" src='{{ "js/jquery/jquery.bidi.js"|m }}'></script>
<script type="text/javascript">
$(document).ready(function() {
  $("select#id_ui_lang option").filter(":not([dir])").bidi();
});
</script>
{% endif %}
{% endblock %}

templates/profiles/profile_detail.html
{% extends "user_profile_base.html"  %}
{% load i18n baseurl %}

{% block title %}
{% ifequal user profile.user %}
    {{ block.super }} » {% trans "Dashboard" %}
{% else %}
    {{ settings.TITLE }}: {% trans "Users" %} » {{ username }}
{% endifequal %}
{% endblock %}

{% block bodyclass %}dashboard{% endblock %}

{% block breadcrumb_content %}
{% ifequal user profile.user %}
    {{ block.super }} » {% trans "Dashboard" %}
{% else %}
    {{ profile.user }}
{% endifequal %}
{% endblock %}

{% block content %}
<div class="module first" lang="{{ LANGUAGE_CODE }}">
    <div class="hd">
        <h2>{% trans "Quick Links" %}</h2>
    </div>
    <div class="bd">
    {% if profile.getquicklinks %}
        {% for language in profile.getquicklinks %}
        <dl class="languagelist">
            <dt class="language">
                <a href="{% filter l %}/{{ language.code }}/{% endfilter %}">{{ language.name }}</a>
                {% ifequal user profile.user %}
                {% if language.islangadmin %}
                    <span class="adminlink">(<a href="{% filter l %}/{{ language.code }}/admin.html{% endfilter %}">{% trans "Admin" %}</a>)</span>
                {% endif %}
                {% endifequal %}
            </dt>
            {% for project in language.projects %}
            <dd>
            <a href="{% filter l %}/{{ language.code }}/{{ project.code }}/{% endfilter %}">{{ project.name }}</a>
            {% ifequal user profile.user %}
            {% if project.isprojectadmin %}
                <span class="adminlink">(<a href="{% filter l %}/{{ language.code }}/{{ project.code }}/admin_permissions.html{% endfilter %}">{% trans "Permissions" %}</a> | <a href="{% filter l %}/{{ language.code }}/{{ project.code }}/admin_files.html{% endfilter %}">{% trans "Files" %}</a>)</span>
            {% endif %}
            {% endifequal %}
            </dd>
            {% endfor %}
        </dl>
        {% endfor %}
    {% else %}
        {% ifequal user profile.user %}
        <p><a href='{{ "/accounts/edit/"|l }}'>{% trans "No languages or projects selected. Choose yours now." %}</a></p>
        {% else %}
        {% trans "This user has not selected languages or projects yet." %}
        {% endifequal %}
    {% endif %}
    </div>
</div>
{% endblock %}

{% block postcontent %}
<div class="module" lang="{{ LANGUAGE_CODE }}">
  <div class="hd">
    <h2>{% trans "User Statistics" %}</h2>
  </div>
  <div class="bd">
    <table>
      {% for stat in profile.getuserstatistics %}
      <tr>
        <th scope="row">{{ stat.text }}</th><td class="stats-number">{{ stat.count }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>
</div>
{% if user.is_superuser %}{% ifequal user profile.user %}
<div style="clear: {% if LANGUAGE_BIDI %}left{% else %}right{% endif %};" ></div>
{% include "admin/rss_widget.html" %}
{% endifequal %}{% endif %}
{% endblock %}

templates/profiles/profile_list.html
{% extends "base.html"  %}
{% load i18n baseurl %}

{% block content %}

<div> 
    <p>{% trans "Profiles list" %}</p>
    
    <table border="0" cellpadding="5" cellspace="5" width="100%">
        <tr>
            <th>{% trans "Username" %}</th>
            <th>{% trans "First name" %}</th>
            <th>{% trans "Last name" %}</th>
        </tr>
        <tr><td colspan="4"><hr width="75%" align="left"></td></tr>
        {% for profile in object_list %}  
        <tr>
            <td><a href="{% filter l %}/accounts/{{ profile.user.username }}/{% endfilter %}">
                    {{ profile.user.username }}
            </a></td>
            <td>{{ profile.user.first_name }}</td>
            <td>{{ profile.user.last_name }} </td>
        </tr>
        {% endfor %}

    </table>
</div>

{% endblock %}